name: Bump Homebrew Formula

on:
  repository_dispatch:
    types: [bump-homebrew]

  workflow_dispatch:

jobs:
  bump:
    name: Bump Formula
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bump version
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: markit
          homebrew-tap: Nightstack/homebrew-markit
          tag-name: ${{ github.event.client_payload.tag }}
          download-url: https://github.com/Nightstack/markit/archive/refs/tags/${{ github.event.client_payload.tag }}.tar.gz
          commit-message: "Bump markit to ${{ github.event.client_payload.tag }}"
          base-branch: main
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
